var first_name="Tiger";
var last_name="Shroff";
console.log(first_name);
console.log(last_name);
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=20;
var b=70;
var mul=a*b;
console.log(mul);
var div=a/b;
console.log(div);